### ISSUE TITLE
could not import C

### ISSUE THREAD

**Issue by jinliming2** [go101/golds#10]
```bash
root@9f31100ac3ac:/project# golds -gen -dir=/root/w .
/project/cbrotli/cgo.go:13:8: could not import C (no metadata for C)
exit for above errors
```

Can I skip a specified subpackage when generating doc for the project?

**Comment by go101** [comment]
To investigate this problem, I need to confirm some things:
* Is there some cgo code in your project? 
* Does `CGO_ENABLED=0 golds -gen -dir=/root/w .` also report the same error?
* Have you installed the gcc toolchain? If not, does the problem still exist after installing gcc? (If your OS is Debian-based, it is best to install `build-essential`.)

If the solutions mentioned in the last two questions still don't help, I'm afraid I couldn't do any more help here, for the Golds project uses [golang.org/x/tools/go/packages](https://pkg.go.dev/golang.org/x/tools/go/packages) to parse code. I must wait the upstream to resolve this problem.

**Comment by jinliming2** [comment]
`apt install build-essential libbrotli-dev` (`libbrotli-dev` for `cbrotli`) works for me.
