### ISSUE TITLE
Option to avoid outputting to a subdirectory

### ISSUE THREAD

**Issue by alecthomas** [go101/golds#14]
Or preferably, just don't output to a subdirectory at all - the user already controls the flag, so they can specify whatever directory they prefer.

When I use `-dir=docs` I expect that the docs will actually be in _that_ directory, not a subdirectory. This is unintuitive as-is, but also causes actual problems when trying to deploy docs through CI because the general expectation is that the CI pipeline can point to a static directory and just push it up to the documentation site. As the sub-directory changes on each invocation, this expectation is broken.

**Comment by go101** [comment]
Good advice, though there is a small incompatibility problem caused by this behavior change, I think the change is worthy to make.

The behavior will not change if the `-dir` option is not presented.

**Comment by go101** [comment]
This should be fixed in tip.

**Comment by alecthomas** [comment]
Brilliant thanks, I'll give it a shot this week.

**Comment by alecthomas** [comment]
This works perfectly, thanks!

**Comment by go101** [comment]
OK. I will close this issue.
