### ISSUE TITLE
Escaping HTML tags

### ISSUE THREAD

**Issue by homsterius** [go101/golds#27]
There is js code in code example "_autoescaping" that is actually executing on the page https://docs.go101.org/std/pkg/html/template.html and showing alert with message "you have been pwned".

**Comment by zigo101** [comment]
@homsterius 

This problem was fixed in https://github.com/go101/golds/commit/def83132fa974d980d50ed83518fb95a73734e5d
But I forgot to update the online demo website.
I will update it soon.

Thanks for this finding!

**Comment by zigo101** [comment]
It is updated now.
The cache expiration duration is 3d, so you might need to refresh that page to avoid the popup.
