### ISSUE TITLE
Support dark theme

### ISSUE THREAD

**Issue by haunt98** [go101/golds#35]
I think it's nice to have to browsing go docs in dark theme!

**Comment by zigo101** [comment]
Thanks for the suggestion.

This will be supported.

**Comment by zigo101** [comment]
@haunt98 The dark theme is supported since v0.5.8. You can use `-theme=dark` option to enable it.

**Comment by haunt98** [comment]
Looking so far so good! Thank you @go101 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/5424272/224658105-6744f666-b1f1-4812-ac71-8b58187d52bd.png">
