### ISSUE TITLE
Panic with go 1.21

### ISSUE THREAD

**Issue by thielepaul** [go101/golds#41]
When I use golds with go 1.21, I always get: `panic: ParsePackages: dependency package cmp not found`

Here is a one-liner to reproduce the issue: `docker run --rm -it golang:1.21 bash -c "git clone https://github.com/go101/golds.git && cd golds && go run . ."`

**Comment by go101** [comment]
Have you re-run the following command after installing Go 1.21?

```shell
go install go101.org/golds@latest
```

**Comment by zigo101** [comment]
Thanks for the report. I will try to fix this problem soon.

**Comment by zigo101** [comment]
Progress: it looks that the pseudo-package `builtin` imports Go 1.21 introduced `cmp` package (it is a really weird design).

Will fix it soon.

**Comment by zigo101** [comment]
@thielepaul 
This problem has been fixed in v0.6.6.

**Comment by thielepaul** [comment]
Thanks a lot for fixing it so fast!
