### ISSUE TITLE
footer option doesn't work

### ISSUE THREAD

**Issue by rutigl** [go101/golds#43]
version Golds v0.6.7
According to help:
 -footer-showing=verbose+qrcode|verbose|simple|none
                Specify how page footers should be shown.
                Available values (default is verbose+qrcode):
                * none: show nothing.
                * simple: show Golds version only.
                * verbose: also show Golds author.
                  promotion info.
                * verbose+qrcode: include verbose content
                  and a qr-code.
I tried 
-footer-showing=none
then
-footer-showing=simple
It doesn't work.
Always shows verbose+qrcode

**Comment by zigo101** [comment]
@rutigl 
I'm sorry that this is a mistake in help. The option name is actually `footer`.
It was ever called `footer-showing` but I forgot to change it in help.

The bug was just fixed in v0.6.8.

Many thanks for this finding!
