### ISSUE TITLE
panic: should not

### ISSUE THREAD

**Issue by 3052** [go101/golds#46]
~~~
> golds -gen -dir=generated -nouses ./...
panic: should not

goroutine 1869 [running]:
go101.org/golds/internal/server.(*docServer).tryRetrievingWorkdingDirectoryModuleInfo(0xc00015a000, 0xc01a07b200, 0x0?)
        D:/Desktop/golds-develop/internal/server/info_module.go:638 +0x13b8
go101.org/golds/internal/server.(*docServer).tryToCompleteModuleInfo(0x0?, 0x0?, 0x0?)
        D:/Desktop/golds-develop/internal/server/info_module.go:301 +0xc5
go101.org/golds/internal/server.(*docServer).analyze.func3.1(0x0?)
        D:/Desktop/golds-develop/internal/server/server.go:303 +0x25
go101.org/golds/code.(*CodeAnalyzer).confirmPackageModules.func1()
        D:/Desktop/golds-develop/code/code-parse.go:717 +0x54
created by go101.org/golds/code.(*CodeAnalyzer).confirmPackageModules in goroutine 1
        D:/Desktop/golds-develop/code/code-parse.go:715 +0x17a6
~~~

https://go101.org/apps-and-libs/golds.html

**Comment by zigo101** [comment]
The panic happens when your module directory is not within the git repository root directory.
One possibility is the git repository root directory is a sub-directory of your module directory. 

Maybe this check in Golds is unnecessary.

I just made a new commit which disables the check. You can try it by running `go install -x go101.org/golds@develop`.
You can let me know if there are still problems.

**Comment by 3052** [comment]
> The panic happens when your module directory is not within the git repository root directory.

no. in my case they are the same.

> One possibility is the git repository root directory is a sub-directory of your module directory.

no. in my case they are the same.

> I just made a new commit which disables the check.

yes, this fixes it, but given the above comments misunderstanding the cause of the problem, I am concerned that the fix might be premature.

**Comment by zigo101** [comment]
@3052 Did you deleted the last comment?

That check only matters when the `-source-code-reading=external` option is used.

You said the two directories are the same. So I just pushed a new commit, which will print the two directories
when the check fails and the `-verbose` option is provided. You can run `golds -verbose -gen -dir=generated -nouses ./...`
to print the two directories (the message lines starting with `info_module.go:638:`).

**Comment by 3052** [comment]
yeah sorry I did delete the comment. I was concerned about the fix, but I guess its "good enough", because it got it working. my bigger concern at this point is the design, as its quite different from the current "official" doc site, and even quite different from the old "godoc.org" as well. without the option to use something similar to one of those, I am going to have to seek another tool at this time, as the current design is just too different in a way I dont like.

thanks for fixing the bug though.
