### ISSUE TITLE
module path is mismatching

### ISSUE THREAD

**Issue by shockerli** [go101/golds#6]
go version: 1.13.7

```
$ go get -u go101.org/gold      
go: extracting go101.org/gold v0.1.5
go get: go101.org/gold@v0.1.5: parsing go.mod:
        module declares its path as: go101.org/golds
                but was required as: go101.org/gold
```

**Comment by go101** [comment]
Sorry, the tool name was changed from `gold` to `golds` recently.
But not all docs has been updated yet.

You can run `go get -u go101.org/golds` to install this tool now.
Or if you prefer the name `gold`, you can run `go get -u go101.org/golds/gold` instead.

BTW, do you copy the command from the Go 101 book?

**Comment by go101** [comment]
BTW, this tool must be built with Go 1.14+.

**Comment by shockerli** [comment]
`go get -u go101.org/golds` is ok. 
And Go 1.13 still install success.
THX
