### ISSUE TITLE
Run golds command

### ISSUE THREAD

**Issue by dd8888** [go101/golds#7]
I cannot get to run golds, or maybe I just didn't understand how to do it.

On my projects directory: 
- I set the go111module environment variable as on
- I run "go get -u go101.org/golds" and everything seems fine.
 
Now if I run the command "golds ." I get the error "command not found: golds". 

Am I missing something? Thank you in advance.

**Comment by go101** [comment]
The `go get` command will install binaries into the `bin` subfolder under the first path specified in `GOPATH` env var (which default value is `$HOME/go`. So it looks the `$HOME/go/bin` is not set in your `PATH` env var. Could do you check if this is true?

**Comment by go101** [comment]
BTW, you can also set the `GOBIN` env var to a path which is already specified in the `PATH` env var to make `golds` findable.

**Comment by dd8888** [comment]
Thanks for the response! Actually the "golds" command does exist inside de go/bin folder. I made it work by using "/Users/myuser/go/bin/golds ."

**Comment by dd8888** [comment]
Also, is there any way I get only the packages from line 43 to line 47? The ones I created for my project.
<img width="1080" alt="Captura de pantalla 2020-11-18 a las 12 26 18" src="https://user-images.githubusercontent.com/47543076/99390205-86876800-28d8-11eb-98bf-ff98e2da01f6.png">

**Comment by go101** [comment]
>  I made it work by using "/Users/myuser/go/bin/golds ."
You can add `/Users/myuser/go/bin/` to you `PATH` environment variable to run `golds` without the `/Users/myuser/go/bin/` prefix. After the adding, you need to open a new terminal window to apply the change.

> is there any way I get only the packages from line 43 to line 47?
Is it acceptable that if these 5 lines are placed at the beginning of the list?

**Comment by dd8888** [comment]
Ok thank you! 

> Is it acceptable that if these 5 lines are placed at the beginning of the list?
Yes I saw the "-emphasize-wdpkgs" option, I will make it work. Thank you for your time!

**Comment by go101** [comment]
BTW, the "-emphasize-wdpkgs" option only worked for docs-generation mode before. I just pushed a new commit to make it also work for non-docs-generation mode now.
