### ISSUE TITLE
feature request: displaying docs of struct exported methods

### ISSUE THREAD

**Issue by nozhT** [go101/golds#8]
I personally use golds as a more informative alternative of godoc, and its code navigation feature has made it really convenient to inspect libraries.

However I find it a bit bothersome that I need to navigate to a struct export method's implementation just to view its docs.

Having the docs next to the method signature (foldable or not) or as a tooltip displayed when hovering over the method signature would be helpful.

**Comment by go101** [comment]
@nozhT
Thanks for the suggestion.
I will find a way to implement this in a near new version.

**Comment by go101** [comment]
@nozhT
This feature is implemented in v0.1.7. So close it.

**Comment by nozhT** [comment]
Just tried it out and it's working marvelously, thank you!!
